### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/beans/Introspector;

### ISSUE THREAD

**Issue by Obrad29** [boncey/Flickr4Java#263]
### Subject of the issue
I have made project for fetching images from Flickr.com. I have used Flickr4Java library, but got the following issue. 

REST = new REST();
Flickr client = new Flickr(Constants.FLICKR_API_KEY, Constants.FLICKR_SECRET, rest);

Can anyone help me?
Regards

### Your environment
* version of Flickr4Java
* version of JDK

### Steps to reproduce
We test the api on Android TV Emulator

### Actual behaviour
Can't initialize Flickr Api

### Log
```
11-15 09:09:14.727 3521-3521/com.wyfiinc.tvss W/System.err: log4j:WARN Error during default initialization
11-15 09:09:14.727 3521-3521/com.wyfiinc.tvss W/System.err: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/beans/Introspector;
11-15 09:09:14.728 3521-3521/com.wyfiinc.tvss W/System.err:     at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:140)
11-15 09:09:14.728 3521-3521/com.wyfiinc.tvss W/System.err:     at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
11-15 09:09:14.728 3521-3521/com.wyfiinc.tvss W/System.err:     at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:805)
11-15 09:09:14.728 3521-3521/com.wyfiinc.tvss W/System.err:     at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
11-15 09:09:14.728 3521-3521/com.wyfiinc.tvss W/System.err:     at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:648)
11-15 09:09:14.728 3521-3521/com.wyfiinc.tvss W/System.err:     at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:514)
11-15 09:09:14.728 3521-3521/com.wyfiinc.tvss W/System.err:     at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:580)
11-15 09:09:14.728 3521-3521/com.wyfiinc.tvss W/System.err:     at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
11-15 09:09:14.728 3521-3521/com.wyfiinc.tvss W/System.err:     at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
11-15 09:09:14.728 3521-3521/com.wyfiinc.tvss W/System.err:     at org.apache.log4j.LogManager.getLogger(LogManager.java:228)
11-15 09:09:14.728 3521-3521/com.wyfiinc.tvss W/System.err:     at org.apache.log4j.Logger.getLogger(Logger.java:117)
11-15 09:09:14.728 3521-3521/com.wyfiinc.tvss W/System.err:     at com.flickr4java.flickr.REST.<clinit>(REST.java:46)
11-15 09:09:14.728 3521-3521/com.wyfiinc.tvss W/System.err:     at com.wyfiinc.tvss.libraries.network.flickr.api.FlickrApi.<init>(FlickrApi.java:33)
11-15 09:09:14.728 3521-3521/com.wyfiinc.tvss W/System.err:     at com.wyfiinc.tvss.libraries.network.flickr.api.FlickrApi.getInstance(FlickrApi.java:42)

```

**Comment by boncey** [comment]
Sorry, F4J doesn't support Android natively.
Please see #137 for more details.
