### ISSUE TITLE
Deepfake error

### ISSUE THREAD

**Issue by Cat-b-o-y** [boncey/Flickr4Java#435]
![image](https://user-images.githubusercontent.com/81151165/111961575-7366ed80-8aae-11eb-87d3-15a7e0ba0e2d.png)
/content/sample_data/cd.mp4
ffprobe -v error -select_streams v -of default=noprint_wrappers=1:nokey=1 -show_entries stream=r_frame_rate /content/sample_data/cd.mp4
	Pre-processing: start...
----------------------MetaProcess----------------------
meta_input:
	path: /content/sample_data/person.jpg
	bg_path: 
	name: 
primitives_dir: ./results/primitives/
processed_dir: ./results/primitives/processed
vid_info_path: ./results/primitives/processed/vid_info.pkl
-------------------------------------------------------
	has_run_detector: True
	has_run_cropper: True
	has_run_3dpose: True
	has_find_front: True
	has_run_parser: True
	has_run_inpaintor: True
	has_run_deform: True
	has_finished: True
----------------------MetaProcess----------------------
meta_input:
	path: /content/sample_data/cd.mp4
	bg_path: 
	name: cd.mp4
	audio: ./results/primitives/cd.mp4/processed/audio.mp3
	fps: 29.97002997002997
	pose_fc: 300
	cam_fc: 100
primitives_dir: ./results/primitives/cd.mp4
processed_dir: ./results/primitives/cd.mp4/processed
vid_info_path: ./results/primitives/cd.mp4/processed/vid_info.pkl
-------------------------------------------------------
	has_run_detector: True
	has_run_cropper: True
	has_run_3dpose: True
	has_find_front: False
	has_run_parser: False
	has_run_inpaintor: False
	has_run_deform: False
	has_finished: True
		Pre-processing: digital deformation start...
		Pre-processing: digital deformation completed...
the current number of sources are 1, while the pre-defined number of sources are 2. 
	Pre-processing: successfully...
Step 2: running personalization on
Step 2: personalization done, saved in ./results/models/Unique_0/personalized.pth...
Step 3: running imitator.
Network AttLWB-SPADE was created
Loading net from ./results/models/Unique_0/personalized.pth
Model Imitator was created
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:3385: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn("Default grid_sample and affine_grid behavior has changed "
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/iPERCore/iPERCore/services/run_imitator.py", line 182, in <module>
    run_imitator(opt=OPT)
  File "/content/iPERCore/iPERCore/services/run_imitator.py", line 171, in run_imitator
    all_meta_outputs = imitate(opt)
  File "/content/iPERCore/iPERCore/services/run_imitator.py", line 128, in imitate
    ref_info = ref_proc_info.convert_to_ref_info()
  File "/content/iPERCore/iPERCore/services/options/process_info.py", line 146, in convert_to_ref_info
    ref_infos = read_ref_infos(self.vid_infos)
  File "/content/iPERCore/iPERCore/services/options/process_info.py", line 170, in read_ref_infos
    assert len(smpls) == len(valid_img_names), f"the length of smpls = {len(smpls)} != the length of " \
AssertionError: the length of smpls = 2297 != the length of images = 2244.

**Comment by Cat-b-o-y** [comment]
AssertionError: the length of smpls = 2297 != the length of images = 2244.
