### ISSUE TITLE
minecraft server error

### ISSUE THREAD

**Issue by Elixsirr** [boncey/Flickr4Java#683]
### minecraft server
The problem that occurs when starting the server
help me

### Your environment
*  jdk-17.0.2

### Log
```
Checking libraries, please wait...
Libraries JSON version: 1.0
The libraries are up to date
Patching server... 100% [============================] 6/6 (0:00:00 / 0:00:00)
Patching complete! Starting server...
Checking for updates...
[Magma] No update found, latest version: (4b3dbc21) current version: (4b3dbc21)
[18:19:28] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: arg                                                                                        s [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.39-4b3dbc21                                                                                        , --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup,                                                                                         net.minecraftforge]
[18:19:28] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.1.3+8.1.3+                                                                                        main-8.1.x.c94d18ec starting: java version 17.0.2 by Oracle Corporation
[18:19:28] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[18:19:28] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/storage/minecraft2/Server/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.
[18:19:30] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, .]
[18:19:41] [modloading-worker-0/INFO] [ne.mi.co.ForgeMod/FORGEMOD]: Forge mod loading, version 36.2.39-4b3dbc21, for MC 1.16.5 with MCP 20210115.111550
[18:19:41] [modloading-worker-0/INFO] [ne.mi.co.MinecraftForge/FORGE]: MinecraftForge v36.2.39-4b3dbc21 Initialized
[18:19:41] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/maven/net/minecraftforge/forge/prom
[18:19:43] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Found status: AHEAD Current: 36.2.39-4b3dbc21 Target: null
[18:19:47] [main/INFO] [mojang/YggdrasilAuthenticationService]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHosraftservices.com', name='PROD'
[18:19:47] [main/INFO] [minecraft/MinecraftServer]: Found new data pack file/bukkit, loading it automatically
[18:19:48] [main/INFO] [minecraft/SimpleReloadableResourceManager]: Reloading ResourceManager: Default, forge-1.16.5-36.2.39-4b3dbc21-universal.jar, bukkit
[18:19:50] [Worker-Main-4/INFO] [minecraft/RecipeManager]: Loaded 7 recipes
[18:19:53] [main/INFO] [or.ma.ma.pa.PatcherManager/]: 3 patches loaded!
[18:19:53] [main/INFO] [or.ma.ma.pa.PatcherManager/]: dynmap [Remaps BukkitVersionHelperCB and BukkitVersionHelperGeneric to support Magma version] loaded
[18:19:53] [main/INFO] [or.ma.ma.pa.PatcherManager/]: Essentials [Fixes for Essentials] loaded
[18:19:53] [main/INFO] [or.ma.ma.pa.PatcherManager/]: WorldEdit [Patches WorldEdit] loaded
[18:19:54] [Server thread/INFO] [minecraft/DedicatedServer]: Starting minecraft server version 1.16.5
[18:19:54] [Server thread/INFO] [minecraft/DedicatedServer]: Loading properties
[18:19:54] [Server thread/INFO] [Minecraft/]: This server is running Magma version git-Magma-1.16.5-4b3dbc21 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT
[18:19:55] [Server thread/INFO] [Minecraft/]: Debug logging is enabled
[18:19:55] [Server thread/INFO] [/]: Server Ping Player Sample Count: 12
[18:19:55] [Server thread/INFO] [Minecraft/]: Using 4 threads for Netty based IO
[18:19:55] [Server thread/INFO] [minecraft/DedicatedServer]: Default game type: SURVIVAL
[18:19:55] [Server thread/INFO] [minecraft/MinecraftServer]: Generating keypair
[18:19:55] [Server thread/INFO] [minecraft/DedicatedServer]: Starting Minecraft server on *:25565
[18:19:55] [Server thread/INFO] [minecraft/NetworkSystem]: Using epoll channel type
[18:19:56] [Server thread/WARN] [minecraft/DedicatedServer]: **** FAILED TO BIND TO PORT!
[18:19:56] [Server thread/WARN] [minecraft/DedicatedServer]: The exception was: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
[18:19:56] [Server thread/WARN] [minecraft/DedicatedServer]: Perhaps a server is already running on that port?
[18:19:56] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[18:19:56] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[18:19:56] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[18:19:56] [Server thread/ERROR] [minecraft/MinecraftServer]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.server.ServerWorld.func_175723_af()" because "serverworld1" is null
        at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:657) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:708) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71260_j(DedicatedServer.java:641) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:913) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:286) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:833) [?:?] {}


```

**Comment by Elixsirr** [comment]
another server was turned on. fuck
